[project]
name = "proto"
version = "0.1.0"
description = "Protocol buffer definitions and generated code for environments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.74.0",
    "grpcio-tools>=1.74.0",
    "protobuf>=5.29.0",
    "mypy-protobuf>=3.6.0",
]

[dependency-groups]
dev = [
    "grpcio>=1.74.0",
    "grpcio-tools>=1.74.0", 
    "protobuf>=5.29.0",
    "mypy-protobuf>=3.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/proto"]
