[project]
name = "core"
version = "0.1.0"
description = "Core functionality for environments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "proto",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/core"]

[tool.uv.sources]
proto = { workspace = true }
